In [1]:
import pandas as pd
import numpy as np

In [2]:
calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)

print(myvar)

day1    420
day2    380
day3    390
dtype: int64

In [13]:
df = pd.DataFrame(myvar)

In [8]:
calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories, index = ["day1", "day3"])

print(myvar)

day1    420
day3    390
dtype: int64

In [20]:
myvar

day1    420
day3    390
dtype: int64

In [21]:
data = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}

df = pd.DataFrame(data)
df

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  6 non-null      int64
 1   Pulse     6 non-null      int64
 2   Maxpulse  6 non-null      int64
 3   Calories  6 non-null      int64
dtypes: int64(4)
memory usage: 240.0+ bytes

In [25]:
newdf=df.dropna()

In [26]:
newdf

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300

In [32]:
print("hello abhay")

hello abhay

In [35]:
newdf.corr()

          Duration     Pulse  Maxpulse  Calories
Duration  1.000000 -0.397151 -0.801471  0.261111
Pulse    -0.397151  1.000000  0.353347  0.766156
Maxpulse -0.801471  0.353347  1.000000 -0.237011
Calories  0.261111  0.766156 -0.237011  1.000000

In [43]:
newdf.to_csv("trt.csv")

In [45]:
newdf.describe()

        Duration       Pulse    Maxpulse    Calories
count   6.000000    6.000000    6.000000    6.000000
mean   55.000000  109.666667  143.333333  369.333333
std     7.745967    6.501282   17.557525   75.152290
min    45.000000  102.000000  127.000000  282.000000
25%    48.750000  104.500000  131.250000  310.000000
50%    60.000000  109.500000  140.000000  373.000000
75%    60.000000  115.250000  147.250000  408.250000
max    60.000000  117.000000  175.000000  479.000000